"""Wiki allowlists: how-to + countries + a curated city set (no pin gazetteers).

Hitchwiki / Trashwiki / Nomadwiki books are shaped as:
practice (generic how-to) → places (Europe first, then North America and
the rest of the Americas, then other regions; each country, then its main
cities) → optional extras (`03-resources`, `03-stories`) → outlook
(original close: go do this, keep the wiki alive). Part intros and outlook
chapters are locked originals, not wiki fetches.

Policy for what belongs in a book (and what must never be compiled) is in
EDITORIAL.md — “Which pages to use”. Change lists here; change the rules there.
"""

from pathlib import Path
import re

from common import slugify

WIKIS = {
    "hitchwiki": {
        "api": "https://hitchwiki.org/en/api.php",
        "origin": "https://hitchwiki.org/en/",
        "dump": "https://dumps.hitchwiki.org/hitchwiki-current-en.xml.gz",
        "howto_categories": ["Category:General info"],
        "country_categories": ["Category:Countries"],
        "book": "hitchhikers-guide",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Hitchwiki:"),
        "skip_titles": (
            "Hitchhiking news and news archive",
        ),
    },
    "trashwiki": {
        "api": "https://trashwiki.org/api.php",
        "origin": "https://trashwiki.org/en/",
        "dump": None,
        "howto_categories": ["Category:Dumpster diving", "Category:General info"],
        "country_categories": [
            "Category:Europe",
            "Category:Asia",
            "Category:Africa",
            "Category:North America",
            "Category:South America",
            "Category:Oceania",
        ],
        "book": "dumpster-diving",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Trashwiki:"),
        "skip_titles": (
            "Main Page",
            "Europe",
            "Asia",
            "Africa",
            "Americas",
            "Caribbean",
            "Central America",
            "North America",
            "South America",
            "Oceania",
            "Balkans",
            "Shoplifting",
            "Coles",
            "IGA",
            "Woolworths",
            "Countdown",
            "Bairnsdale",
            "Melbourne",
            "Moe",
            "Morwell",
            "Traralgon",
            "Warrigal",
            "New Jersey",
            "Australian Capital Territory",
            "New South Wales",
            "Northern Territory",
            "Queensland",
            "South Australia",
            "Tasmania",
            "Victoria",
            "Western Australia",
            "News and events",
            "News",
        ),
    },
    "nomadwiki": {
        "api": "https://nomadwiki.org/api.php",
        "origin": "https://nomadwiki.org/en/",
        "dump": "https://dumps.hitchwiki.org/nomadwiki-current.xml.gz",
        "howto_categories": [
            "Category:Transport",
            "Category:Food",
            "Category:Money",
            "Category:Accommodation",
            "Category:Equipment",
            "Category:Health",
            "Category:Volunteering",
            "Category:Law",
            "Category:Culture",
        ],
        "country_categories": ["Category:Countries"],
        "book": "shoestring-nomad",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Nomadwiki:"),
        "stub_if_title_contains": ("hitchhik", "dumpster", "hospitality exchange", "couchsurf"),
    },
    "trustroots": {
        "api": "https://wiki.trustroots.org/api.php",
        "origin": "https://wiki.trustroots.org/en/",
        "dump": "https://dumps.hitchwiki.org/trustroots-current.xml.gz",
        "howto_titles": [
            "How to write a hosting request",
            "How to be a good guest",
            "How to be a good host",
            "How To Create A Good Profile",
            "How to write a request",
            "How to add my place",
            "How to organize a camp",
            "How to handle Couchscroogers",
            "How to handle freeloaders",
            "Searching and requesting a couch",
            "How to search for a couch on CouchSurfing",
            "Start Rooting",
            "Circles",
            "Safety",
            "Host",
            "Profiles",
            "A brief history of hospitality exchange networks",
            "Hospitality exchange is more than CouchSurfing",
            "Hospitality exchange",
            "Hospitality Club",
            "Hospitality Club censorship",
            "BeWelcome",
            "History of BeWelcome",
            "Philosophy of BeWelcome",
            "History of Trustroots",
            "Couchers",
            "Couchsurfing",
            "Servas",
            "List of hospitality exchange networks",
            "List of projects related to Hospitality Exchange",
            "P2P Hospitality initiatives and proposals",
            "Academic research about hospitality exchange",
            "Replace CouchSurfing",
            "Volunteer",
            "Anarchists",
            "Rural hospitality",
            "HospitalityGuide.net",
        ],
        "howto_categories": [],
        "country_categories": ["Category:Countries", "Category:Europe", "Category:Asia"],
        "book": "hospitality-exchange",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Trustroots Wiki:"),
    },
}

DRUPAL_SITES = {
    "random-roads": {
        "base": "https://randomroads.org",
        "list_paths": ["/stories"],
        "book": "random-roads",
        "lang": "en",
        "article_path_re": r"^/story/",
        "max_list_pages": 20,
        "skip_path_contains": ("/books", "/book/", "/feed", "/rss", "/file/", "/postcard"),
    },
    "dumpsterdam": {
        "base": "https://dumpsterdam.nl",
        "list_paths": ["/", "/nieuws"],
        "book": "dumpsterdam",
        "lang": "nl",
        "article_path_re": r"^/(article|artikel|dumpsterdam|gratis-|nieuwe-|restival|too-good|een-|gleaners|het-|afval-|over|links|contact|dumpster-|video-|photos/)",
        "max_list_pages": 15,
        "skip_path_contains": ("/feed", "/rss", "/user", "/file/", "/tag/", "/users/"),
    },
    "moneyless-en": {
        "base": "https://moneyless.org",
        "list_paths": ["/", "/tips", "/about"],
        "book": "moneyless",
        "lang": "en",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/book/", "/feed", "/rss", "/user", "/tags/", "/contact", "/privacy", "/books"),
    },
    "moneyless-nl": {
        "base": "https://geldloos.nl",
        "list_paths": ["/"],
        "book": "geldloos",
        "lang": "nl",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/feed", "/rss", "/user", "/tags/", "/contact"),
    },
    "moneyless-es": {
        "base": "https://sindinero.net",
        "list_paths": ["/"],
        "book": "sin-dinero",
        "lang": "es",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/feed", "/rss", "/user", "/tags/", "/contact"),
    },
    "casa-robino": {
        "base": "https://casarobino.org",
        "list_paths": ["/"],
        "book": "shoestring-nomad",
        "lang": "en",
        "subdir": "03-stories",
        "article_path_re": r"/\d{4}/\d{2}/",
        "max_list_pages": 20,
        "skip_path_contains": ("/user", "/feed", "/rss", "/category/", "/users/"),
    },
}

# Curated cities differ per book. Spot pins stay on live maps.
CITY_SELECTION = {
    "hitchwiki": [
        "Paris",
        "Amsterdam",
        "Berlin",
        "London",
        "New York City",
        "Barcelona",
        "Rome",
        "Madrid",
        "Vienna",
        "Prague",
        "Warsaw",
        "Budapest",
        "Lisbon",
        "Dublin",
        "Chicago",
        "Los Angeles",
        "San Francisco",
        "Montreal",
        "Toronto",
        "Vancouver",
        "Sydney",
        "Melbourne",
        "Auckland",
        "Istanbul",
        "Bangkok",
        "Mexico City",
        "Buenos Aires",
        "Tokyo",
        "New Delhi",
        "Mumbai",
        "Nairobi",
        "Cape Town",
        "Cairo",
        "Johannesburg",
        "Lagos",
        "Accra",
        "Addis Ababa",
        "Dakar",
        "Casablanca",
        "Beijing",
        "Shanghai",
        "Seoul",
        "Manila",
        "Jakarta",
        "Hanoi",
        "Ho Chi Minh City",
        "Tehran",
        "Moscow",
        "Tbilisi",
        "Kathmandu",
        "Lima",
        "Bogotá",
        "Santiago",
        "Rio de Janeiro",
        "São Paulo",
        "Kuala Lumpur",
        "Singapore",
        "Hong Kong",
    ],
    "trashwiki": [
        "Amsterdam",
        "Berlin",
        "Paris",
        "London",
        "New York City",
        "Copenhagen",
        "Rotterdam",
        "Hamburg",
        "Brussels",
        "Stockholm",
        "Munich",
        "Leipzig",
        "Cologne",
        "Lyon",
        "Marseille",
        "Barcelona",
        "Madrid",
        "Rome",
        "Vienna",
        "Prague",
        "Warsaw",
        "Budapest",
        "Lisbon",
        "Porto",
        "Valencia",
        "Dublin",
        "Edinburgh",
        "Manchester",
        "Helsinki",
        "Oslo",
        "Athens",
        "Istanbul",
        "Tel Aviv",
        "Tbilisi",
        "Chicago",
        "Los Angeles",
        "San Francisco",
        "Seattle",
        "Montreal",
        "Toronto",
        "Vancouver",
        "Melbourne",
        "Auckland",
        "Wellington",
        "Mexico City",
        "Tokyo",
        "Rio de Janeiro",
        "São Paulo",
        "Singapore",
    ],
    "nomadwiki": [
        "Paris",
        "Amsterdam",
        "Berlin",
        "London",
        "New York City",
        "Barcelona",
        "Madrid",
        "Lisbon",
        "Dublin",
        "Vienna",
        "Prague",
        "Budapest",
        "Warsaw",
        "Athens",
        "Istanbul",
        "Tbilisi",
        "Tel Aviv",
        "Jerusalem",
        "Beijing",
        "Hong Kong",
        "Singapore",
        "Melbourne",
        "Sydney",
        "Auckland",
        "Montreal",
    ],
}

CITY_ALIASES = {
    "New York City": ("New York City", "New York", "NYC"),
    "Mumbai": ("Mumbai", "Bombay"),
    "Bogotá": ("Bogotá", "Bogota"),
    "Ho Chi Minh City": ("Ho Chi Minh City", "Saigon"),
    "New Delhi": ("New Delhi", "Delhi"),
    "San Francisco": ("San Francisco", "Bay Area"),
}

# City chapter slug → country title (wiki page name before per-wiki overrides).
CITY_COUNTRY = {
    "accra": "Ghana",
    "addis-ababa": "Ethiopia",
    "amsterdam": "Netherlands",
    "athens": "Greece",
    "auckland": "New Zealand",
    "bangkok": "Thailand",
    "barcelona": "Spain",
    "bay-area": "United States of America",
    "beijing": "China",
    "berlin": "Germany",
    "bogota": "Colombia",
    "bogotá": "Colombia",
    "brussels": "Belgium",
    "budapest": "Hungary",
    "buenos-aires": "Argentina",
    "cairo": "Egypt",
    "cape-town": "South Africa",
    "casablanca": "Morocco",
    "chicago": "United States of America",
    "cologne": "Germany",
    "copenhagen": "Denmark",
    "dakar": "Senegal",
    "dublin": "Ireland",
    "edinburgh": "United Kingdom",
    "hamburg": "Germany",
    "hanoi": "Vietnam",
    "helsinki": "Finland",
    "ho-chi-minh-city": "Vietnam",
    "hong-kong": "Hong Kong",
    "istanbul": "Turkey",
    "jakarta": "Indonesia",
    "jerusalem": "Israel",
    "johannesburg": "South Africa",
    "kathmandu": "Nepal",
    "kuala-lumpur": "Malaysia",
    "lagos": "Nigeria",
    "leipzig": "Germany",
    "lima": "Peru",
    "lisbon": "Portugal",
    "london": "United Kingdom",
    "los-angeles": "United States of America",
    "lyon": "France",
    "madrid": "Spain",
    "manchester": "United Kingdom",
    "manila": "Philippines",
    "marseille": "France",
    "melbourne": "Australia",
    "mexico-city": "Mexico",
    "montreal": "Canada",
    "moscow": "Russia",
    "mumbai": "India",
    "munich": "Germany",
    "nairobi": "Kenya",
    "new-delhi": "India",
    "new-york": "United States of America",
    "new-york-city": "United States of America",
    "oslo": "Norway",
    "paris": "France",
    "porto": "Portugal",
    "prague": "Czech Republic",
    "rio-de-janeiro": "Brazil",
    "rome": "Italy",
    "rotterdam": "Netherlands",
    "san-francisco": "United States of America",
    "santiago": "Chile",
    "sao-paulo": "Brazil",
    "são-paulo": "Brazil",
    "seattle": "United States of America",
    "seoul": "South Korea",
    "shanghai": "China",
    "singapore": "Singapore",
    "stockholm": "Sweden",
    "sydney": "Australia",
    "tbilisi": "Georgia",
    "tehran": "Iran",
    "tel-aviv": "Israel",
    "tokyo": "Japan",
    "toronto": "Canada",
    "valencia": "Spain",
    "vancouver": "Canada",
    "vienna": "Austria",
    "warsaw": "Poland",
    "wellington": "New Zealand",
}

COUNTRY_TITLE_BY_WIKI = {
    "nomadwiki": {
        "United States of America": "United States",
        "Georgia": "Georgia (country)",
    },
}


def country_slug_for_city(wiki: str, city_title: str) -> str | None:
    slug = slugify(city_title)
    country = CITY_COUNTRY.get(slug)
    if country is None:
        return None
    title = COUNTRY_TITLE_BY_WIKI.get(wiki, {}).get(country, country)
    return slugify(title)


def city_part(wiki: str, city_title: str) -> str:
    """Directory under src/ for a city chapter: 02-countries/<country-slug>."""
    cfg = WIKIS[wiki]
    country = country_slug_for_city(wiki, city_title)
    if not country:
        return f"{cfg['part_country']}/_ungrouped"
    return f"{cfg['part_country']}/{country}"


# Travel order, not A–Z. Europe first, then North America and the rest of
# the Americas, then Asia, Africa, Oceania. Within a country, CITY_RANK
# puts capitals and the main cities first.
COUNTRY_SLUG_ALIASES = {
    "united-states": "united-states-of-america",
    "georgia-country": "georgia",
    "macedonia": "north-macedonia",
    "macao": "macau",
    "aland-islands": "åland-islands",
}

GEO_REGIONS: list[tuple[str, str, tuple[str, ...]]] = [
    (
        "europe",
        "Europe",
        (
            "united-kingdom",
            "england",
            "scotland",
            "wales",
            "northern-ireland",
            "ireland",
            "isle-of-man",
            "jersey",
            "france",
            "monaco",
            "belgium",
            "netherlands",
            "luxembourg",
            "germany",
            "austria",
            "switzerland",
            "liechtenstein",
            "denmark",
            "sweden",
            "norway",
            "finland",
            "iceland",
            "åland-islands",
            "faroe-islands",
            "greenland",
            "spain",
            "portugal",
            "andorra",
            "azores",
            "italy",
            "san-marino",
            "vatican",
            "malta",
            "czech-republic",
            "slovakia",
            "poland",
            "hungary",
            "slovenia",
            "estonia",
            "latvia",
            "lithuania",
            "croatia",
            "bosnia-and-herzegovina",
            "serbia",
            "montenegro",
            "kosovo",
            "north-macedonia",
            "albania",
            "greece",
            "bulgaria",
            "romania",
            "moldova",
            "transnistria",
            "yugoslavia",
            "ukraine",
            "belarus",
            "cyprus",
            "russia",
            "tatarstan",
            "bashkortostan",
        ),
    ),
    (
        "north-america",
        "North America",
        (
            "canada",
            "united-states-of-america",
            "mexico",
            "bermuda",
        ),
    ),
    (
        "central-america",
        "Central America and the Caribbean",
        (
            "guatemala",
            "belize",
            "el-salvador",
            "honduras",
            "nicaragua",
            "costa-rica",
            "panama",
            "cuba",
            "jamaica",
            "haiti",
            "dominican-republic",
            "puerto-rico",
            "bahamas",
            "turks-and-caicos",
            "cayman-islands",
            "antigua-and-barbuda",
            "saint-kitts-and-nevis",
            "guadeloupe",
            "dominica",
            "martinique",
            "saint-lucia",
            "saint-barthélemy",
            "saint-vincent-and-the-grenadines",
            "barbados",
            "grenada",
            "trinidad-and-tobago",
            "curaçao",
            "aruba",
            "united-states-virgin-islands",
            "british-virgin-islands",
            "anguilla",
            "montserrat",
        ),
    ),
    (
        "south-america",
        "South America",
        (
            "colombia",
            "venezuela",
            "guyana",
            "suriname",
            "french-guiana",
            "ecuador",
            "peru",
            "bolivia",
            "brazil",
            "paraguay",
            "chile",
            "argentina",
            "uruguay",
            "falkland-islands",
        ),
    ),
    (
        "asia",
        "Asia",
        (
            "turkey",
            "georgia",
            "abkhazia",
            "armenia",
            "azerbaijan",
            "iran",
            "iraq",
            "syria",
            "lebanon",
            "israel",
            "jordan",
            "saudi-arabia",
            "yemen",
            "oman",
            "united-arab-emirates",
            "qatar",
            "bahrain",
            "kuwait",
            "afghanistan",
            "pakistan",
            "india",
            "nepal",
            "bhutan",
            "bangladesh",
            "sri-lanka",
            "maldives",
            "kazakhstan",
            "kyrgyzstan",
            "tajikistan",
            "turkmenistan",
            "uzbekistan",
            "mongolia",
            "china",
            "tibet",
            "hong-kong",
            "macau",
            "taiwan",
            "north-korea",
            "south-korea",
            "japan",
            "myanmar",
            "laos",
            "vietnam",
            "cambodia",
            "thailand",
            "malaysia",
            "singapore",
            "indonesia",
            "brunei",
            "philippines",
            "timor-leste",
            "british-indian-ocean-territory",
        ),
    ),
    (
        "africa",
        "Africa",
        (
            "morocco",
            "western-sahara",
            "algeria",
            "tunisia",
            "libya",
            "egypt",
            "mauritania",
            "senegal",
            "the-gambia",
            "guinea-bissau",
            "guinea",
            "sierra-leone",
            "liberia",
            "côte-divoire",
            "ghana",
            "togo",
            "benin",
            "nigeria",
            "burkina-faso",
            "mali",
            "niger",
            "cape-verde",
            "cameroon",
            "chad",
            "central-african-republic",
            "republic-of-the-congo",
            "democratic-republic-of-the-congo",
            "gabon",
            "equatorial-guinea",
            "são-tomé-and-príncipe",
            "sudan",
            "south-sudan",
            "eritrea",
            "ethiopia",
            "djibouti",
            "somalia",
            "somaliland",
            "puntland",
            "kenya",
            "uganda",
            "rwanda",
            "burundi",
            "tanzania",
            "angola",
            "zambia",
            "malawi",
            "mozambique",
            "zimbabwe",
            "botswana",
            "namibia",
            "south-africa",
            "lesotho",
            "eswatini",
            "madagascar",
            "mauritius",
            "seychelles",
            "comoros",
        ),
    ),
    (
        "oceania",
        "Oceania",
        (
            "australia",
            "new-zealand",
            "papua-new-guinea",
            "solomon-islands",
            "vanuatu",
            "new-caledonia",
            "fiji",
            "tonga",
            "samoa",
            "american-samoa",
            "tuvalu",
            "kiribati",
            "nauru",
            "marshall-islands",
            "federated-states-of-micronesia",
            "palau",
            "niue",
        ),
    ),
    ("elsewhere", "Elsewhere", ()),
]

# Lower number = earlier. Capitals first, then the cities travellers actually
# use. Unlisted cities sort after these, then by name.
CITY_RANK = {
    "london": 0,
    "edinburgh": 1,
    "manchester": 2,
    "dublin": 0,
    "paris": 0,
    "lyon": 1,
    "marseille": 2,
    "brussels": 0,
    "amsterdam": 0,
    "rotterdam": 1,
    "berlin": 0,
    "hamburg": 1,
    "munich": 2,
    "leipzig": 3,
    "cologne": 4,
    "vienna": 0,
    "copenhagen": 0,
    "stockholm": 0,
    "oslo": 0,
    "helsinki": 0,
    "madrid": 0,
    "barcelona": 1,
    "valencia": 2,
    "lisbon": 0,
    "porto": 1,
    "rome": 0,
    "prague": 0,
    "warsaw": 0,
    "budapest": 0,
    "athens": 0,
    "istanbul": 0,
    "tbilisi": 0,
    "jerusalem": 0,
    "tel-aviv": 1,
    "tehran": 0,
    "moscow": 0,
    "new-delhi": 0,
    "mumbai": 1,
    "kathmandu": 0,
    "beijing": 0,
    "shanghai": 1,
    "hong-kong": 0,
    "seoul": 0,
    "tokyo": 0,
    "bangkok": 0,
    "kuala-lumpur": 0,
    "singapore": 0,
    "jakarta": 0,
    "manila": 0,
    "hanoi": 0,
    "ho-chi-minh-city": 1,
    "cairo": 0,
    "casablanca": 0,
    "dakar": 0,
    "accra": 0,
    "lagos": 0,
    "addis-ababa": 0,
    "nairobi": 0,
    "cape-town": 0,
    "johannesburg": 1,
    "toronto": 0,
    "montreal": 1,
    "vancouver": 2,
    "new-york-city": 0,
    "new-york": 0,
    "los-angeles": 1,
    "chicago": 2,
    "san-francisco": 3,
    "bay-area": 3,
    "seattle": 4,
    "mexico-city": 0,
    "bogotá": 0,
    "bogota": 0,
    "lima": 0,
    "rio-de-janeiro": 0,
    "são-paulo": 1,
    "sao-paulo": 1,
    "santiago": 0,
    "buenos-aires": 0,
    "sydney": 0,
    "melbourne": 1,
    "wellington": 0,
    "auckland": 1,
}

_GEO_INDEX: dict[str, tuple[int, int]] = {}
_REGION_INDEX: dict[str, int] = {}
for _ri, (_rid, _label, _countries) in enumerate(GEO_REGIONS):
    _REGION_INDEX[_rid] = _ri
    for _ci, _slug in enumerate(_countries):
        _GEO_INDEX[_slug] = (_ri, _ci)
        _canon = COUNTRY_SLUG_ALIASES.get(_slug, _slug)
        _GEO_INDEX.setdefault(_canon, (_ri, _ci))
for _alias, _canon in COUNTRY_SLUG_ALIASES.items():
    if _canon in _GEO_INDEX:
        _GEO_INDEX.setdefault(_alias, _GEO_INDEX[_canon])


def canonical_country_slug(slug: str) -> str:
    return COUNTRY_SLUG_ALIASES.get(slug, slug)


def country_geo_index(slug: str) -> tuple[int, int]:
    slug = canonical_country_slug(slug)
    if slug in _GEO_INDEX:
        return _GEO_INDEX[slug]
    return (_REGION_INDEX.get("elsewhere", len(GEO_REGIONS)), 10_000)


def city_rank(slug: str) -> int:
    return CITY_RANK.get(slug, 50)


def geo_src_key(rel: Path) -> tuple:
    """Sort key for src-relative paths: practice, then geo (Europe, then North America), then the rest."""
    parts = Path(rel).parts
    top = parts[0]
    m = re.match(r"^(\d{2})", top)
    part_n = int(m.group(1)) if m else 80
    posix = "/".join(parts)
    if top != "02-countries" and top != "02-countries.md":
        return (part_n, posix)
    if top == "02-countries.md" or len(parts) == 1:
        return (2, -1, 0, 0, 0, "")
    name = Path(parts[-1]).stem
    if name.startswith("_"):
        rid = name[1:]
        return (2, _REGION_INDEX.get(rid, len(GEO_REGIONS)), -1, 0, 0, name)
    if len(parts) == 2:
        ri, ci = country_geo_index(name)
        return (2, ri, ci, 0, 0, name)
    country = parts[1]
    city = name
    ri, ci = country_geo_index(country)
    return (2, ri, ci, 1, city_rank(city), city)

CITY_MAP_LINKS = {
    "hitchwiki": (
        "Roadside hitching spots go stale. For current places to hitch in and "
        "out of this city, use [maps.hitchwiki.org](https://maps.hitchwiki.org/) "
        "and the live Hitchwiki page linked at the end of this chapter. "
        "This book keeps general orientation, not a pin gazetteer."
    ),
    "trashwiki": (
        "Named dumpsters and map pins go stale. For current spots use "
        "[dumpstermap.org](https://dumpstermap.org/) and the live Trashwiki page. "
        "This chapter is culture, legality, and general practice — not a dumpster list."
    ),
    "nomadwiki": (
        "Hostels, camps, and neighbourhood tips change. Use the live "
        "[Nomadwiki](https://nomadwiki.org/) city page for what is current. "
        "This chapter is a snapshot of general orientation, not a pin list."
    ),
}

HOWTO_FALLBACK = {
    "hitchwiki": [
        "Top tips",
        "First time hitchhiking",
        "Hitchhiker's safety",
        "Etiquette",
        "Things to carry",
        "Where to hitchhike",
        "Hitchhiking techniques",
        "Highway",
        "Signs",
        "Appearance",
        "Hitchhiking at night",
        "Maps",
        "Waiting",
        "Hitchhiking",
    ],
    "trashwiki": [
        "Dumpster diving",
        "Legal",
        "Safety",
        "Technique",
        "Equipment",
        "Food",
        "How to dumpster dive",
    ],
}
