"""Wiki allowlists: how-to + countries + a curated city set (no pin gazetteers).

Hitchwiki / Trashwiki / Nomadwiki books are shaped as:
practice (generic how-to) → places (each country, then its cities) → outlook
(original close: go do this, keep the wiki alive). Part intros and outlook
chapters are locked originals, not wiki fetches.

Policy for what belongs in a book (and what must never be compiled) is in
EDITORIAL.md — “Which pages to use”. Change lists here; change the rules there.
"""

from common import slugify

WIKIS = {
    "hitchwiki": {
        "api": "https://hitchwiki.org/en/api.php",
        "origin": "https://hitchwiki.org/en/",
        "dump": "https://dumps.hitchwiki.org/hitchwiki-current-en.xml.gz",
        "howto_categories": ["Category:General info"],
        "country_categories": ["Category:Countries"],
        "book": "hitchhikers-guide",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Hitchwiki:"),
    },
    "trashwiki": {
        "api": "https://trashwiki.org/api.php",
        "origin": "https://trashwiki.org/en/",
        "dump": None,
        "howto_categories": ["Category:Dumpster diving", "Category:General info"],
        "country_categories": [
            "Category:Europe",
            "Category:Asia",
            "Category:Africa",
            "Category:North America",
            "Category:South America",
            "Category:Oceania",
        ],
        "book": "dumpster-diving",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Trashwiki:"),
        "skip_titles": (
            "Main Page",
            "Europe",
            "Asia",
            "Africa",
            "Americas",
            "Caribbean",
            "Central America",
            "North America",
            "South America",
            "Oceania",
            "Balkans",
            "Shoplifting",
            "Coles",
            "IGA",
            "Woolworths",
            "Countdown",
            "Bairnsdale",
            "Melbourne",
            "Moe",
            "Morwell",
            "Traralgon",
            "Warrigal",
            "New Jersey",
            "Australian Capital Territory",
            "New South Wales",
            "Northern Territory",
            "Queensland",
            "South Australia",
            "Tasmania",
            "Victoria",
            "Western Australia",
        ),
    },
    "nomadwiki": {
        "api": "https://nomadwiki.org/api.php",
        "origin": "https://nomadwiki.org/en/",
        "dump": "https://dumps.hitchwiki.org/nomadwiki-current.xml.gz",
        "howto_categories": [
            "Category:Transport",
            "Category:Food",
            "Category:Money",
            "Category:Accommodation",
            "Category:Equipment",
            "Category:Health",
            "Category:Volunteering",
            "Category:Law",
            "Category:Culture",
        ],
        "country_categories": ["Category:Countries"],
        "book": "shoestring-nomad",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "part_city": "03-cities",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Nomadwiki:"),
        "stub_if_title_contains": ("hitchhik", "dumpster", "hospitality exchange", "couchsurf"),
    },
    "trustroots": {
        "api": "https://wiki.trustroots.org/api.php",
        "origin": "https://wiki.trustroots.org/en/",
        "dump": "https://dumps.hitchwiki.org/trustroots-current.xml.gz",
        "howto_titles": [
            "How To Write A Couch Request",
            "How to write a hosting request",
            "How To Be A Good Guest",
            "How To Be A Good Host",
            "How To Create A Good Profile",
            "How to write a request",
            "How to add my place",
            "How to organize a camp",
            "How to handle Couchscroogers",
            "How to handle freeloaders",
            "Searching and requesting a couch",
            "How to search for a couch on CouchSurfing",
            "Start Rooting",
            "Circles",
            "Safety",
            "Host",
            "Hosting",
            "Profiles",
            "A Brief History of Hospitality Exchange Networks",
            "Hospitality exchange is more than CouchSurfing",
            "Hospitality exchange",
            "Hospitality Club",
            "Hospitality Club censorship",
            "BeWelcome",
            "History of BeWelcome",
            "Philosophy of BeWelcome",
            "History of Trustroots",
            "Couchers",
            "CouchSurfing",
            "Servas",
            "List of hospitality exchange networks",
            "List of projects related to Hospitality Exchange",
            "P2P Hospitality initiatives and proposals",
            "Academic research about hospitality exchange",
            "Replace CouchSurfing",
            "CouchSurfing sells out - a message that spreads",
            "Volunteer",
            "Anarchist hosts",
            "Rural hospitality",
            "HospitalityGuide.net",
        ],
        "howto_categories": [],
        "country_categories": ["Category:Countries", "Category:Europe", "Category:Asia"],
        "book": "hospitality-exchange",
        "part_howto": "01-practice",
        "part_country": "02-countries",
        "skip_title_prefixes": ("User:", "Talk:", "File:", "Template:", "Category:", "Trustroots Wiki:"),
    },
}

DRUPAL_SITES = {
    "random-roads": {
        "base": "https://randomroads.org",
        "list_paths": ["/stories"],
        "book": "random-roads",
        "lang": "en",
        "article_path_re": r"^/story/",
        "max_list_pages": 20,
        "skip_path_contains": ("/books", "/book/", "/feed", "/rss", "/file/", "/postcard"),
    },
    "dumpsterdam": {
        "base": "https://dumpsterdam.nl",
        "list_paths": ["/", "/nieuws"],
        "book": "dumpsterdam",
        "lang": "nl",
        "article_path_re": r"^/(article|artikel|dumpsterdam|gratis-|nieuwe-|restival|too-good|een-|gleaners|het-|afval-|over|links|contact|dumpster-|video-|photos/)",
        "max_list_pages": 15,
        "skip_path_contains": ("/feed", "/rss", "/user", "/file/", "/tag/", "/users/"),
    },
    "moneyless-en": {
        "base": "https://moneyless.org",
        "list_paths": ["/", "/tips", "/about"],
        "book": "moneyless",
        "lang": "en",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/book/", "/feed", "/rss", "/user", "/tags/", "/contact", "/privacy", "/books"),
    },
    "moneyless-nl": {
        "base": "https://geldloos.nl",
        "list_paths": ["/"],
        "book": "moneyless",
        "lang": "nl",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/feed", "/rss", "/user", "/tags/", "/contact"),
    },
    "moneyless-es": {
        "base": "https://sindinero.net",
        "list_paths": ["/"],
        "book": "moneyless",
        "lang": "es",
        "article_path_re": r"^/[a-z0-9][a-z0-9-]+$",
        "max_list_pages": 8,
        "skip_path_contains": ("/feed", "/rss", "/user", "/tags/", "/contact"),
    },
    "casa-robino": {
        "base": "https://casarobino.org",
        "list_paths": ["/"],
        "book": "shoestring-nomad",
        "lang": "en",
        "subdir": "03-stories",
        "article_path_re": r"/\d{4}/\d{2}/",
        "max_list_pages": 20,
        "skip_path_contains": ("/user", "/feed", "/rss", "/category/", "/users/"),
    },
}

# Curated cities differ per book. Spot pins stay on live maps.
CITY_SELECTION = {
    "hitchwiki": [
        "Paris",
        "Amsterdam",
        "Berlin",
        "London",
        "New York City",
        "Barcelona",
        "Rome",
        "Madrid",
        "Vienna",
        "Prague",
        "Warsaw",
        "Budapest",
        "Lisbon",
        "Dublin",
        "Chicago",
        "Los Angeles",
        "San Francisco",
        "Montreal",
        "Toronto",
        "Vancouver",
        "Sydney",
        "Melbourne",
        "Auckland",
        "Istanbul",
        "Bangkok",
        "Mexico City",
        "Buenos Aires",
        "Tokyo",
        "New Delhi",
        "Mumbai",
        "Nairobi",
        "Cape Town",
        "Cairo",
        "Johannesburg",
        "Lagos",
        "Accra",
        "Addis Ababa",
        "Dakar",
        "Casablanca",
        "Beijing",
        "Shanghai",
        "Seoul",
        "Manila",
        "Jakarta",
        "Hanoi",
        "Ho Chi Minh City",
        "Tehran",
        "Moscow",
        "Tbilisi",
        "Kathmandu",
        "Lima",
        "Bogotá",
        "Santiago",
        "Rio de Janeiro",
        "São Paulo",
        "Kuala Lumpur",
        "Singapore",
        "Hong Kong",
    ],
    "trashwiki": [
        "Amsterdam",
        "Berlin",
        "Paris",
        "London",
        "New York City",
        "Copenhagen",
        "Rotterdam",
        "Hamburg",
        "Brussels",
        "Stockholm",
        "Munich",
        "Leipzig",
        "Cologne",
        "Lyon",
        "Marseille",
        "Barcelona",
        "Madrid",
        "Rome",
        "Vienna",
        "Prague",
        "Warsaw",
        "Budapest",
        "Lisbon",
        "Porto",
        "Valencia",
        "Dublin",
        "Edinburgh",
        "Manchester",
        "Helsinki",
        "Oslo",
        "Athens",
        "Istanbul",
        "Tel Aviv",
        "Tbilisi",
        "Chicago",
        "Los Angeles",
        "San Francisco",
        "Seattle",
        "Montreal",
        "Toronto",
        "Vancouver",
        "Melbourne",
        "Auckland",
        "Wellington",
        "Mexico City",
        "Tokyo",
        "Rio de Janeiro",
        "São Paulo",
        "Singapore",
    ],
    "nomadwiki": [
        "Paris",
        "Amsterdam",
        "Berlin",
        "London",
        "New York City",
        "Barcelona",
        "Madrid",
        "Lisbon",
        "Dublin",
        "Vienna",
        "Prague",
        "Budapest",
        "Warsaw",
        "Athens",
        "Istanbul",
        "Tbilisi",
        "Tel Aviv",
        "Jerusalem",
        "Beijing",
        "Hong Kong",
        "Singapore",
        "Melbourne",
        "Sydney",
        "Auckland",
        "Montreal",
    ],
}

CITY_ALIASES = {
    "New York City": ("New York City", "New York", "NYC"),
    "Mumbai": ("Mumbai", "Bombay"),
    "Bogotá": ("Bogotá", "Bogota"),
    "Ho Chi Minh City": ("Ho Chi Minh City", "Saigon"),
    "New Delhi": ("New Delhi", "Delhi"),
    "San Francisco": ("San Francisco", "Bay Area"),
}

# City chapter slug → country title (wiki page name before per-wiki overrides).
CITY_COUNTRY = {
    "accra": "Ghana",
    "addis-ababa": "Ethiopia",
    "amsterdam": "Netherlands",
    "athens": "Greece",
    "auckland": "New Zealand",
    "bangkok": "Thailand",
    "barcelona": "Spain",
    "bay-area": "United States of America",
    "beijing": "China",
    "berlin": "Germany",
    "bogota": "Colombia",
    "bogotá": "Colombia",
    "brussels": "Belgium",
    "budapest": "Hungary",
    "buenos-aires": "Argentina",
    "cairo": "Egypt",
    "cape-town": "South Africa",
    "casablanca": "Morocco",
    "chicago": "United States of America",
    "cologne": "Germany",
    "copenhagen": "Denmark",
    "dakar": "Senegal",
    "dublin": "Ireland",
    "edinburgh": "United Kingdom",
    "hamburg": "Germany",
    "hanoi": "Vietnam",
    "helsinki": "Finland",
    "ho-chi-minh-city": "Vietnam",
    "hong-kong": "Hong Kong",
    "istanbul": "Turkey",
    "jakarta": "Indonesia",
    "jerusalem": "Israel",
    "johannesburg": "South Africa",
    "kathmandu": "Nepal",
    "kuala-lumpur": "Malaysia",
    "lagos": "Nigeria",
    "leipzig": "Germany",
    "lima": "Peru",
    "lisbon": "Portugal",
    "london": "United Kingdom",
    "los-angeles": "United States of America",
    "lyon": "France",
    "madrid": "Spain",
    "manchester": "United Kingdom",
    "manila": "Philippines",
    "marseille": "France",
    "melbourne": "Australia",
    "mexico-city": "Mexico",
    "montreal": "Canada",
    "moscow": "Russia",
    "mumbai": "India",
    "munich": "Germany",
    "nairobi": "Kenya",
    "new-delhi": "India",
    "new-york": "United States of America",
    "new-york-city": "United States of America",
    "oslo": "Norway",
    "paris": "France",
    "porto": "Portugal",
    "prague": "Czech Republic",
    "rio-de-janeiro": "Brazil",
    "rome": "Italy",
    "rotterdam": "Netherlands",
    "san-francisco": "United States of America",
    "santiago": "Chile",
    "sao-paulo": "Brazil",
    "são-paulo": "Brazil",
    "seattle": "United States of America",
    "seoul": "South Korea",
    "shanghai": "China",
    "singapore": "Singapore",
    "stockholm": "Sweden",
    "sydney": "Australia",
    "tbilisi": "Georgia",
    "tehran": "Iran",
    "tel-aviv": "Israel",
    "tokyo": "Japan",
    "toronto": "Canada",
    "valencia": "Spain",
    "vancouver": "Canada",
    "vienna": "Austria",
    "warsaw": "Poland",
    "wellington": "New Zealand",
}

COUNTRY_TITLE_BY_WIKI = {
    "nomadwiki": {
        "United States of America": "United States",
        "Georgia": "Georgia (country)",
    },
}


def country_slug_for_city(wiki: str, city_title: str) -> str | None:
    slug = slugify(city_title)
    country = CITY_COUNTRY.get(slug)
    if country is None:
        return None
    title = COUNTRY_TITLE_BY_WIKI.get(wiki, {}).get(country, country)
    return slugify(title)


def city_part(wiki: str, city_title: str) -> str:
    """Directory under src/ for a city chapter: 02-countries/<country-slug>."""
    cfg = WIKIS[wiki]
    country = country_slug_for_city(wiki, city_title)
    if not country:
        return f"{cfg['part_country']}/_ungrouped"
    return f"{cfg['part_country']}/{country}"

CITY_MAP_LINKS = {
    "hitchwiki": (
        "Roadside hitching spots go stale. For current places to hitch in and "
        "out of this city, use [maps.hitchwiki.org](https://maps.hitchwiki.org/) "
        "and the live Hitchwiki page linked at the end of this chapter. "
        "This book keeps general orientation, not a pin gazetteer."
    ),
    "trashwiki": (
        "Named dumpsters and map pins go stale. For current spots use "
        "[dumpstermap.org](https://dumpstermap.org/) and the live Trashwiki page. "
        "This chapter is culture, legality, and general practice — not a dumpster list."
    ),
    "nomadwiki": (
        "Hostels, camps, and neighbourhood tips change. Use the live "
        "[Nomadwiki](https://nomadwiki.org/) city page for what is current. "
        "This chapter is a snapshot of general orientation, not a pin list."
    ),
}

HOWTO_FALLBACK = {
    "hitchwiki": [
        "Top Tips",
        "First time hitchhiking",
        "Hitchhiker's safety",
        "Safety",
        "Etiquette",
        "What to pack",
        "Where to hitchhike",
        "Techniques",
        "Highway",
        "Signs",
        "Appearance",
        "Night hitchhiking",
        "Maps",
        "Waiting",
        "Women",
        "Hitchhiking",
    ],
    "trashwiki": [
        "Dumpster diving",
        "Legal",
        "Safety",
        "Technique",
        "Equipment",
        "Food",
        "How to dumpster dive",
    ],
}
